config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # ресурсное объявление экшенов для контроллера comments
  resources :articles do
  	resources :comments
  end
  resources :tags, only: [:show]
  resources :articles, only: [:show, :index]

  # редиректы и пути страниц сайта
  get '/draft' => 'articles#draft'
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :comments, dependent: :destroy
  	validates :title, presence: true, length: { minimum: 1, maximum: 70 }


    def all_tags
    	self.tags.map(&:name).join(', ')
    end

    def all_tags=(names)
    	self.tags = names.split(',').map do |name|
    		Tag.where(name: name.strip).first_or_create!
    	end
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
	# before_destroy :can_destroy?

	belongs_to :article
	belongs_to :user

	def can_destroy?
		if true
			throw :abort
		end
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  def meta_title(title)
    ['Блог', title].reject(&:empty?).join(' - ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]


  def index
    @articles = Article.where(:visible => true).paginate(page: params[:page], :per_page => 5)
  end

  def draft
    @meta_title  = meta_title 'Мои статьи'
    @articles = Article.paginate(page: params[:page], :per_page => 5)
  end

  def show
    if @article.visible == true
      if @article.meta_title_articles.blank?
        @meta_title = meta_title @article.title
      else
         @meta_title = meta_title @article.meta_title_articles
      end
    else
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end
  # создание статьи
  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id

    if params[:draft]
      @article.visible = false
    end

    if @article.save && @article.visible == false
      redirect_to draft_path, notice: 'Статья была успешно добавлена в черновики'
    elsif @article.save && @article.visible == true
      redirect_to root_path, notice: 'Статья была успешно добавлена'
    else 
      render :new
    end
  end

  def update
    if params[:draft]
      @article.visible = false
    else
      @article.visible = true
    end
    if @article.update(article_params)
      redirect_to root_path, notice: 'Статья была успешно изменена'
    else
      render :edit
    end
  end

  def destroy
    if @article.present?
      @article.destroy
    end
     
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :author, :all_tags, :visible, :author_id)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	# создание коментария
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
	# удаление коментария
	def destroy 
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		# получение параметров коментария
	    def comment_params
	    	params.require(:comment).permit(:body, :user_id).merge({user_id: current_user.id})
	    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# Выведение карты сайта в корень проекта
	def sitemap
		respond_to do |format|
			format.xml { render file: 'public/sitemaps/sitemap.xml' }
			format.html { redirect_to root_url }
		end
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id])
		@articles = @tag.articles
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.haml
=form_for [@article], html: { multipart: true } do |f|
	.input-field
		=f.label 'Название статьи'
		=f.text_field :title
	.input-field
		=f.label 'Автор(ы) статьи'
		=f.text_field :author
	.input-field
		%em
			Статья
		=f.trix_editor :body, :class => 'editor'
	.input-field
		=f.label 'Теги статьи'
		=f.text_field :all_tags

	.input-feild.links
		=f.submit 'Опубликовать', :class => 'btn left'
		=f.submit 'Сохранить в черновик', :class => 'btn right', :name => 'draft'

app/views/articles/draft.html.haml
.content.row
	- @articles.order(id: :desc).each do |article|
		- if user_signed_in? && article.author_id == current_user.id
			.post.col.s12
				.title.row
					%h4.col.m10.offset-m1.s12
						- if article.visible == true
							= link_to article.title, article_path(article)
						- else
							= link_to article.title, edit_article_path(article)
					- if article.visible == false
						%h6.col.m10.offset-m1.s12
							Не опубликовано
					.tags_articles.col.m10.s12.offset-m1
						= raw article.tags.map(&:name).map{ |t| link_to t, tag_path(t)}.join(' ')
				.text.row
					.links.col.m10.s12.offset-m1
						.date.right
							%span
								= article.created_at.to_date.strftime("%d.%m.%Y")
						.left
							- if article.visible == true
								= link_to 'Читать', article_path(article)
								|
							- if user_signed_in? && article.author_id == current_user.id
								= link_to 'Удалить', article_path(article), method: :delete, data: { confirm: 'Вы уверены?'}
								|
								= link_to 'Изменить', edit_article_path(article)

app/views/articles/edit.html.haml
.content.row
	%h3 Редактирование
	.col.s12.form
		= render "form"

app/views/articles/index.html.haml
.content.row		
	= render(:partial => "tags/tags_cloud")
	- @articles.order(id: :desc).each do |article|
		.post.col
			.title.row
				%h4.col.m8.offset-m1.s12
					= link_to article.title, article_path(article)
				.col.m4.s12.offset-m1
					%span
						= User.find(article.author_id).email
				.tags_articles.col.m10.s12.offset-m1
					= raw article.tags.map(&:name).map{ |t| link_to t, tag_path(t)}.join(' ')
			.text.row
				.links.col.m10.s12.offset-m1
					.date.right
						%span
							= article.created_at.to_date.strftime("%d.%m.%Y")
					.left
						= link_to 'Читать', article_path(article)
						- if user_signed_in? && article.author_id == current_user.id
							|
							= link_to 'Удалить', article_path(article), method: :delete, data: { confirm: 'Вы уверены?'}
							|
							= link_to 'Изменить', edit_article_path(article)
	= will_paginate @articles, :class => 'col s12'

app/views/articles/new.html.haml
.content.row
	%h3.col.s12 Добавление статьи
	.col.s12.form
		= render "form"

app/views/articles/show.html.haml
.content.row
	.article.col.s12
		%h3.center
			= @article.title
		.body.row
			.col.m10.s12.offset-m1
				= @article.body.html_safe
	.author.col.s12
		%p.col.s10.offset-m1
			Автор(ы):
			= @article.author
		%h4
			Коментарии
		- @article.comments.each do |comment| 
			%h5
				= User.find(comment.user_id).email
			%p
				= comment.body
			- if user_signed_in? && comment.user_id == current_user.id
				%p
					= link_to 'Удалить коментарий', [comment.article, comment], method: :delete
		- if user_signed_in?
			%h4
				Добавить коментарий:
			= form_for([@article, @article.comments.build]) do |f| 
				.input-field
					= f.label :body
					= f.text_area :body, :class => 'materialize-textarea'
				%p
					= f.submit 'Добавить коментарий', :class => 'btn'
	= link_to '< Назад', root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
	<head>
		<title><%= @meta_title ? @meta_title : 'Блог' %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div class="container">
			<p class="notice"><%= notice %></p>
	    	<p class="alert"><%= alert %></p>
	    	<%= render(:partial => "partials/header") %>
			<div class="col s12">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/partials/_header.html.haml
%header.row
	%nav
		.nav-wrapper
			%ul.hide-on-med-and-down
				%li
					= link_to 'Главная', root_path, :class => 'hover'
				%li	
					- if user_signed_in?
						= link_to 'Добавить статью', new_article_path(@new), :class => 'hover'
				%li	
					- if user_signed_in?
						= link_to 'Мои статьи', draft_path, :class => 'hover'
				%li.auth
					- if user_signed_in?
						= link_to 'Выход', destroy_user_session_path, method: :delete, :class => 'hover'
					- else
						= link_to 'Вход', new_user_session_path, :class => 'hover'
						= link_to 'Регистрация', new_user_registration_path, :class => 'hover'

app/views/tags/_tags_cloud.html.haml
.tag_cloud.col.s3.right
	.row.title
		%h4.col.m12.offset-m1.s12
			Теги
	.tags.col.m10.offset-m1.s12
		- tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|
			= link_to tag.name, tag_path(tag.name), class: css_class

app/views/tags/show.html.haml
.content.row	
	%h2
		= @tag.name
	- if @tag.articles.empty?
		%h4 Статей нет
	- else
		= render @tag.articles.order(id: :desc)